version: "3.8"

networks:
  traefik-network:
    driver: overlay
    external: true

  db-network:
    driver: overlay
    external: true

services:
  adminer:
    image: adminer
    networks:
      - traefik-network
      - db-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-network"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        # 
        - "traefik.http.routers.adminer.rule=Host(`adminer.${DOMAIN}`)"
        - "traefik.http.routers.adminer.entrypoints=web"
        - "traefik.http.routers.adminer.middlewares=redirect-to-https@docker"
        # 
        - "traefik.http.services.adminer-svc.loadbalancer.server.port=8080"
        # 
        - "traefik.http.routers.adminer-secured.rule=Host(`adminer.${DOMAIN}`)"
        - "traefik.http.routers.adminer-secured.entrypoints=websecured"
        - "traefik.http.routers.adminer-secured.tls=true"
        - "traefik.http.routers.adminer-secured.tls.certresolver=myhttpchallenge"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
