version: "3.8"

networks:
  traefik-network:
    driver: overlay
    external: true

  db-network:
    driver: overlay
    external: true

services:
  sidekiq:
    image: tanngoc93/com.thedogpaws.coupon:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      DB_POOL:     "${RAILS_DB_POOL}"
      DB_PORT:     "${RAILS_DB_PORT}"
      DB_HOST:     "${RAILS_DB_HOST}"
      DB_USER:     "${RAILS_DB_USER}"
      DB_PASSWORD: "${RAILS_DB_PASSWORD}"
      DB_FOR_PROD: "${RAILS_DB_PROD}"
      REDIS_HOST:  "${REDIS_HOST}"
      RAILS_ENV:   "${RAILS_ENV}"
      RACK_ENV:    "${RACK_ENV}"
      PLATFORM:    "${RAILS_PLATFORM}"
      PORT:        "${PORT}"
    networks:
      - traefik-network
      - db-network
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=false"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
